'use strict';
const $=s=>document.querySelector(s),main=$('#main'),about=main.innerHTML,reduced=matchMedia('(prefers-reduced-motion: reduce)'),mediaDialog=$('#media-dialog'),progressDialog=$('#progress-dialog');
let mediaToken=0;
let content,current='sobre-mim',changing=false,hlsPlayer=null,scrollFrame=0,observer=null;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const folderIcon='<svg viewBox="0 0 24 20" fill="none" aria-hidden="true"><path d="M1 5V1h8l3 4h11v14H1z" stroke="currentColor" stroke-width="1.5"/><path d="M1 6h22" stroke="currentColor" stroke-width="1.5"/></svg>';
function dissolve(overlay){return new Promise(resolve=>{if(reduced.matches){overlay.remove();resolve();return}const color=getComputedStyle(overlay).backgroundColor,canvas=document.createElement('canvas'),w=innerWidth,h=innerHeight,size=32;canvas.width=w;canvas.height=h;overlay.replaceChildren(canvas);overlay.style.background='transparent';const ctx=canvas.getContext('2d'),cells=[];for(let y=0;y<h;y+=size)for(let x=0;x<w;x+=size)cells.push({x,y,delay:Math.random()*430,drift:(Math.random()-.5)*65});const start=performance.now();function frame(now){let t=now-start;ctx.clearRect(0,0,w,h);ctx.fillStyle=color;for(const c of cells){const p=Math.max(0,Math.min(1,(t-c.delay)/500));if(p<1){ctx.globalAlpha=1-p;ctx.fillRect(c.x+c.drift*p,c.y+p*p*85,size*(1-p*.6)+1,size*(1-p*.6)+1)}}if(t<950)requestAnimationFrame(frame);else{overlay.remove();resolve()}}requestAnimationFrame(frame)})}
async function transition(red,fn){changing=true;const overlay=document.createElement('div');overlay.className='pixel-overlay theme-transition';overlay.style.background=getComputedStyle(document.body).getPropertyValue('--accent');overlay.innerHTML=`<div class="transition-logo"><img src="media/Logo.svg" width="130" height="130" alt=""><span>${red?'AAA JESSE OWENS':'ARTHUR BÚRIGO'}</span></div>`;document.body.append(overlay);await new Promise(r=>setTimeout(r,reduced.matches?0:330));document.body.classList.toggle('red-theme',red);fn();await dissolve(overlay);changing=false}
function setupMotion(){observer?.disconnect();const nodes=main.querySelectorAll('.reveal');if(!reduced.matches){observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.04,rootMargin:'0px 0px -25px 0px'});nodes.forEach(n=>observer.observe(n))}else nodes.forEach(n=>n.classList.add('visible'));main.querySelectorAll('.portrait-card').forEach(card=>{card.addEventListener('pointermove',event=>{if(reduced.matches||event.pointerType==='touch')return;const r=card.getBoundingClientRect(),x=(event.clientX-r.left)/r.width,y=(event.clientY-r.top)/r.height;card.style.setProperty('--origin',`${x*100}% ${y*100}%`);card.style.setProperty('--rx',`${(y-.5)*-5}deg`);card.style.setProperty('--ry',`${(x-.5)*5}deg`)});card.addEventListener('pointerleave',()=>{card.style.removeProperty('--rx');card.style.removeProperty('--ry')})});updateScroll()}
function updateScroll(){cancelAnimationFrame(scrollFrame);scrollFrame=requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;$('#scroll-progress').style.width=`${max>0?scrollY/max*100:0}%`})}
addEventListener('scroll',updateScroll,{passive:true});addEventListener('resize',updateScroll);
function countMedia(folder){return folder.media.length+folder.children.reduce((n,c)=>n+countMedia(c),0)}
function time(seconds){return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`}
function renderGallery(tab,path){let node=tab,trail=[tab.slug],navigation='';for(let level=0;level<5&&node.children.length;level++){const choice=path[level+1]||(!node.media.length?node.children[0].slug:'');const base=trail.join('/');navigation+=`<nav class="sub-nav level-${level}" aria-label="${escapeHTML(node.name)} — subpastas">${node.media.length?`<a href="#${base}" class="sub-item ${!choice?'selected':''}" ${!choice?'aria-current="page"':''}>Principal</a>`:''}${node.children.map(c=>`<a href="#${base}/${c.slug}" class="sub-item ${choice===c.slug?'selected':''}" ${choice===c.slug?'aria-current="page"':''}>${folderIcon}${escapeHTML(/^\d+$/.test(c.name)?'Série '+c.name:c.name)}</a>`).join('')}</nav>`;const child=node.children.find(c=>c.slug===choice);if(!child)break;node=child;trail.push(child.slug)}
const metadata={'aaa-jesse-owens':'CAMPANHAS · DESIGN · AUDIOVISUAL','naapi':'DESIGN · EXPERIÊNCIA DE MARCA','dolly-rebranding':'IDENTIDADE VISUAL','ai-creative':'EXPERIMENTAÇÃO CRIATIVA','europe':'DESIGN · AUDIOVISUAL'};
main.innerHTML=`<section class="project-view"><div class="project-heading reveal"><div><div class="eyebrow">${metadata[tab.slug]||'PROJETOS SELECIONADOS'}</div><h1>${escapeHTML(tab.name)}</h1></div><div class="project-total">${String(countMedia(tab)).padStart(2,'0')}<span>ARQUIVOS</span></div></div>${navigation}<div class="gallery-heading"><h2>${node===tab?'Arquivos do projeto':escapeHTML(/^\d+$/.test(node.name)?'Série '+node.name:node.name)}</h2><span>${String(node.media.length).padStart(2,'0')} arquivos</span></div><div class="gallery">${node.media.map((m,i)=>{const wide=m.width/m.height>1.5||(m.kind==='video'&&m.width>m.height),portrait=m.height>m.width;return `<article class="media-card reveal ${wide?'wide-card':''} ${portrait?'portrait-card':''}" style="--delay:${i%3*65}ms"><div class="mini-title"><span>${escapeHTML(m.name)}</span><span aria-hidden="true">${m.kind==='video'?'▶':'↗'}</span></div><button class="media-button ${m.kind==='video'?'video-button':''}" data-media="${i}" aria-label="${m.kind==='video'?'Reproduzir vídeo':'Ampliar imagem'}: ${escapeHTML(m.name)}"><img src="${escapeHTML(m.kind==='video'?m.poster:m.src)}" alt="${escapeHTML(m.name)}" width="${m.width}" height="${m.height}" ${i<2?'fetchpriority="high"':'loading="lazy"'} decoding="async">${m.kind==='video'?'<span class="play-badge" aria-hidden="true">▶</span>':''}</button><div class="card-footer"><span>${m.kind==='video'?'FILME':'DESIGN'} <span class="file-dimensions">/ ${m.width} × ${m.height}</span></span><span>${m.kind==='video'&&m.duration?time(m.duration):String(i+1).padStart(2,'0')}</span></div></article>`}).join('')}</div><a class="back-top" href="#top" data-top>↑ Voltar ao topo</a></section>`;
main.querySelectorAll('[data-media]').forEach(button=>button.addEventListener('click',()=>openMedia(node.media[Number(button.dataset.media)])));main.querySelector('[data-top]').addEventListener('click',e=>{e.preventDefault();scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'})});setupMotion()}
function render(path){const tab=content.tabs.find(t=>t.slug===path[0])||content.tabs[0];current=tab.slug;document.querySelectorAll('.nav-item').forEach(a=>{const active=a.hash==='#'+current;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#location-name').textContent=path.join(' / ');$('#location-info').textContent=current==='sobre-mim'?'um pouco sobre mim':`${countMedia(tab)} arquivos` ;$('#footer-location').textContent=tab.name.toUpperCase();document.title=`${tab.name} — Arthur Búrigo`;if(current==='sobre-mim'){main.innerHTML=about;main.querySelector('.portrait-window').classList.add('reveal');main.querySelector('.about-copy').classList.add('reveal');setupMotion()}else renderGallery(tab,path);scrollTo({top:0,behavior:'instant'})}
async function navigate(initial=false){if(!content||changing)return;const path=decodeURIComponent(location.hash.slice(1)||'sobre-mim').split('/');if(path[0]==='main'||path[0]==='top')return;if(path[0]==='vibecode'){progressDialog.showModal();document.body.classList.add('dialog-open');history.replaceState(null,'','#'+current);return}const red=path[0]==='aaa-jesse-owens';if(!initial&&red!==document.body.classList.contains('red-theme'))await transition(red,()=>render(path));else{document.body.classList.toggle('red-theme',red);render(path)}}
document.addEventListener('click',event=>{const a=event.target.closest('a[href^="#"]');if(!a)return;if(a.hash==='#vibecode'){event.preventDefault();progressDialog.showModal();document.body.classList.add('dialog-open')}else if(changing)event.preventDefault()});addEventListener('hashchange',()=>navigate());
let hlsLibrary;
function loadHls(){return hlsLibrary??=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='vendor/hls.min.js';script.onload=()=>resolve(window.Hls);script.onerror=reject;document.head.append(script)})}
async function openMedia(m){const token=++mediaToken;$('#media-title').textContent=m.name;$('#media-error').hidden=true;const stage=$('#media-stage');stage.replaceChildren();if(m.kind==='video'){const video=document.createElement('video');video.controls=true;video.playsInline=true;video.preload='metadata';video.poster=m.poster;video.setAttribute('aria-label',m.name);stage.append(video);mediaDialog.showModal();document.body.classList.add('dialog-open');let fallback=false;const play=()=>video.play().catch(()=>{});const useMp4=()=>{if(!mediaDialog.open||token!==mediaToken)return;fallback=true;hlsPlayer?.destroy();hlsPlayer=null;if(!m.src){$('#media-error').hidden=false;return}video.src=m.src;play()};video.addEventListener('error',()=>{if(!fallback&&m.hls)useMp4();else $('#media-error').hidden=false});if(m.hls&&video.canPlayType('application/vnd.apple.mpegurl')){video.src=m.hls;play()}else if(m.hls){try{const Hls=await loadHls();if(!mediaDialog.open||token!==mediaToken)return;if(Hls.isSupported()){hlsPlayer=new Hls({maxBufferLength:20});hlsPlayer.loadSource(m.hls);hlsPlayer.attachMedia(video);hlsPlayer.on(Hls.Events.MANIFEST_PARSED,play);hlsPlayer.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)useMp4()})}else useMp4()}catch{useMp4()}}else useMp4()}else{const img=new Image();img.src=m.src;img.alt=m.name;img.onerror=()=>$('#media-error').hidden=false;stage.append(img);mediaDialog.showModal();document.body.classList.add('dialog-open')}}
for(const dialog of [mediaDialog,progressDialog]){dialog.querySelectorAll('.close-dialog').forEach(button=>button.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.classList.remove('dialog-open');if(dialog===mediaDialog){mediaToken++;hlsPlayer?.destroy();hlsPlayer=null;const video=dialog.querySelector('video');if(video){video.pause();video.removeAttribute('src');video.load()}$('#media-stage').replaceChildren()}})}
async function boot(){const loader=$('#loader');let progress=0,target=10;document.body.classList.add('loading');const interval=setInterval(()=>{progress=Math.min(target,progress+3);$('#loading-fill').style.width=progress+'%';$('#loading-value').textContent=Math.floor(progress)+'%';$('.loading-track').setAttribute('aria-valuenow',Math.floor(progress))},30);try{const [data]=await Promise.all([fetch('data.json').then(r=>{if(!r.ok)throw Error('Content unavailable');target=45;return r.json()}),document.fonts.ready.then(()=>target=Math.max(target,65)),Promise.all([...document.images].map(img=>img.decode().catch(()=>{}))).then(()=>target=Math.max(target,85))]);content=data;target=100;await new Promise(r=>setTimeout(r,reduced.matches?0:1100));progress=100;$('#loading-fill').style.width='100%';$('#loading-value').textContent='100%';$('.loading-track').setAttribute('aria-valuenow','100');clearInterval(interval);await new Promise(r=>setTimeout(r,reduced.matches?0:200));await navigate(true);await dissolve(loader)}catch(error){clearInterval(interval);loader.remove();main.insertAdjacentHTML('beforeend','<p class="load-error">Não foi possível abrir as galerias. <button onclick="location.reload()">Tentar novamente</button></p>')}finally{document.body.classList.remove('loading')}}boot();
